# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dffd8b64067a1839d0a5262b85b55c1087aee3c934d5a8723b2080b61ed9d2b3a529f1591ea86741d4be0330dc8ec39a7d6f0fc85b9ef1cbaec1014106a65a34

test:
  secret_key_base: 5eda6bd7c1c0db8f80a35b26560897f456a96c81f18e9adf4781236f17714f32c1ce0c0d8a52e0089fb8d4b29d669e1df17be1e300882d889512518043a90560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
